security:
  password_hashers:
    App\Entity\User:
      algorithm: auto

  providers:
    app_user_provider:
      entity:
        class: App\Entity\User
        property: email

  firewalls:
    dev:
      pattern: ^/(_(profiler|wdt)|css|images|js)/
      security: false

    main:
      lazy: true
      provider: app_user_provider
      custom_authenticators:
        - App\Security\LoginAuthenticator
      entry_point: App\Security\LoginAuthenticator
      logout:
        path: app_logout
        # where to redirect after logout
        # target: app_any_route

  access_control:
    - { path: ^/login, roles: PUBLIC_ACCESS }
    - { path: ^/admin, roles: ROLE_ADMIN }
    - { path: ^/dashboard, roles: IS_AUTHENTICATED_FULLY }